source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/HuiYouHua/HHYSpecs.git'


use_frameworks!

platform :ios, '8.0'

target 'HHYFMMain_Example' do
  pod 'HHYFMMain', :path => '../'

  target 'HHYFMMain_Tests' do
    inherit! :search_paths

    
  end
end
